Add and correct view modes for rendering pages and venue for search indexing
localgovdrupal/localgov_directories pull request #110
Opened 2021-06-02 12:17 UTC by ekes

Pages was using the default template, which could have been causing content to get missed.
Venue was good, but included the titles of the fields that's just repeated words not related to the content, and rendered some things unnecessarily.

Helps #73

2021-07-20 09:19 UTC, ekes commented
Oh! Is this still not a thing. Adding @stephen-cox @Adnan-cds @andybroomfield for review then!

2021-07-29 13:04 UTC, stephen-cox requested changes
Couple of IDs to remove, but otherwise looks fine just from reviewing the config.

2021-07-29 13:04 UTC, stephen-cox commented on modules/localgov_directories_venue/config/install/core.entity_view_display.node.localgov_directories_venue.directory_index.yml
> +uuid: 4d6ed028-e23c-4552-b9fc-f9103df429fa
Don't think this should be here

2021-07-29 13:04 UTC, stephen-cox commented on modules/localgov_directories_venue/config/install/core.entity_view_display.node.localgov_directories_venue.directory_index.yml
> +  default_config_hash: yuSNmUeMHlWYAbP3Wezm7Ijgp8IkvQa9TREh5dYZ-qI
Should be remove as well

2021-09-06 14:23 UTC, ekes commented
So changes are now only hiding the labels from the exisiting indexd view mode for venue, and adding the equivalent to the page.

2021-09-07 17:18 UTC, Adnan-cds commented
I am happy for it to be merged once Steve approves it.

2021-09-08 16:08 UTC, stephen-cox approved these changes
I'm happy - let's merge

2021-09-27 13:35 UTC, finnlewis approved these changes
This looks good to me.

2021-09-27 13:35 UTC, merged