Add optional support for localgov_scarfolk theme block placement out …
localgovdrupal/localgov_directories pull request #159
Opened 2021-10-04 14:20 UTC by finnlewis

…of the box.

2021-10-05 14:13 UTC, stephen-cox requested changes
While installing this with the profile branch that enables the Scarfolk theme and the Demo content module I see the following error message repeated twice. 

```
[error]  Block localgov_directories_channel_search_block is missing.  Cannot update its visibility settings.
```

Looks like the `CHANNEL_SEARCH_BLOCK` constant needs to be updated as well.

https://github.com/localgovdrupal/localgov_directories/blob/4ceaf0b1f73dce5e536c400cc6b7096c1be31ae4/src/Constants.php#L14

2021-10-05 14:13 UTC, stephen-cox commented on config/optional/block.block.localgov_directories_facets.yml
>  provider: null
This file should be renamed to  `config/optional/block.block.localgov_directories_facets_scarfolk.yml` to match the block ID.

2021-10-05 15:22 UTC, finnlewis commented on config/optional/block.block.localgov_directories_facets.yml
>  provider: null
Thanks @stephen-cox - I'd missed a commit and push. Please see now, added two new files for the localgov_scarfolk theme config.

2021-10-05 15:23 UTC, finnlewis commented
Thanks @stephen-cox I'd missed a commit, should be good now.

2021-10-05 15:25 UTC, finnlewis commented
Actually - what about the `CHANNEL_SEARCH_BLOCK` ? It seems to work without changing that now, as I've not changed the id of the original block.

2021-10-05 15:28 UTC, finnlewis commented
Looking at the code, I think the block id is unchanged, as 
`localgov_directories_channel_search_block` 
even if the config id changes.

Both configs reference the same actual block plugin: 

https://github.com/localgovdrupal/localgov_directories/blob/feature/158-scarfolk/config/optional/block.block.localgov_directories_channel_search_block.yml#L14

https://github.com/localgovdrupal/localgov_directories/blob/feature/158-scarfolk/config/optional/block.block.localgov_directories_channel_search_block_scarfolk.yml#L14

2021-10-05 22:26 UTC, finnlewis commented
Keen to merge this unless there are any objections.

2021-10-06 09:06 UTC, finnlewis commented
@ekes any thoughts on the above?

2021-10-06 09:36 UTC, ekes commented
> @ekes any thoughts on the above?

I can have a review of all that conditional config logic, and block placement, but @Adnan-cds probably already remembers it, so might be better placed for a quick answer.

2021-10-06 09:45 UTC, stephen-cox approved these changes
Looking good now

2021-10-06 09:47 UTC, finnlewis commented
Thanks @stephen-cox ! This is why two pairs of eyes are good!

2021-10-06 09:47 UTC, merged