Facet weight
localgovdrupal/localgov_directories pull request #48
Opened 2020-11-04 19:01 UTC by Adnan-cds

- Added a "weight" field to both the localgov_directories_facets content entity and localgov_directories_facets_type config entity.
- A facet sort plugin that respects the weight property of localgov_directoires_facets entities.
- An update hook to "activate" the above.
- Convinced our custom [facet template preprocessor](https://github.com/localgovdrupal/localgov_directories/blob/f68e7d5e0952534ff14317cf6a12690aba2b29cc/src/DirectoryExtraFieldDisplay.php#L249) to respect the weight property of the localgov_directories_facets_type entities.

### Improvement ideas
- A Functional test to verify that the Facets are indeed rendered based on their weight.  I will raise a separate ticket for this.
- I haven't added any default weight to **existing** localgov_directories_facets entities (i.e. Facet items).  Migration should do this for us.  But I can add one if there is enough demand for it.

Resolves #35

2020-11-06 08:56 UTC, stephen-cox requested changes
Hi @Adnan-cds 

The code for this looks fine, but I have queries regarding the functionality.

It looks to be possible to order the facet types using a draggable interface but not the facet items, so to change these content editors will need to manually set this be editing the facet item. Is that correct? This is not a major problem as it would be quite a big overhaul of the facet item interface to implement a draggable way to set weights on these; although grouping facet items by their type would be a big improvement to the editor experience.

The main issue I find is the default behaviour when all the facet weights are set to 0. Before saving the facet type order these display on a directory channel page in a random order. Facet items are also randomly ordered. If content editors don't want to set the weight on these things I would expect them to display alphabetically. So there needs to be two sorts applied; weight and then alphabetical for equally weighted items.

If you can add this second sort then I'm happy to approve this.

2020-11-06 10:51 UTC, Adnan-cds commented
> It looks to be possible to order the facet types using a draggable interface but not the facet items

That's right.  Drupal core comes with a [Draggable list class](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Config%21Entity%21DraggableListBuilder.php/class/DraggableListBuilder/9.0.x) for config entities but not content entities.  That stopped me from implementing the dragging functionality for the Facet items.  It is still possible to achieve this through a custom list built on top of Drupal core's [tabledrag](https://api.drupal.org/api/drupal/core%21includes%21common.inc/function/drupal_attach_tabledrag/9.0.x) functionality.  That will be a UX improvement for editors but won't change the facet behaviour.  Perhaps we can implement this as part of a separate ticket since it is not blocking the migration of Facet items.

> If you can add this second sort then I'm happy to approve this.

Makes total sense.  I shouldn't have missed this.  I'll update the code and give you a shout.

Thanks for the feedback :)

2020-11-06 13:22 UTC, finnlewis approved these changes
Hi @Adnan-cds and @stephen-cox 

I've tested too and can confirm the functionality works, even if it is all a bit of a UX challenge for site builders to change the ordering. Hopefully we can improve the UX in due course. 

I imagine we will also need to extend the sorting options to for facets within a facet type to include default sorting by alphabetical, by weight and by number of results. The latter is a standard approach with faceted filters which I expect some people will want, such that large result sets can display facet options something like this: 

Colour: 
 - red (738)
 - blue (438)
 - green (37)

But that's for another PR. 

I'm happy with this as is for now.

Thanks @Adnan-cds !

2020-11-06 13:23 UTC, finnlewis commented
Oh - I tested the hook_update_n too - installed the module, created some content and facets, then switched to this branch and ran updb. All seemed to work as expected.

2020-11-06 13:48 UTC, Adnan-cds commented
> facets within a facet type to include default sorting by alphabetical

Thanks Finn.  I hope to restore the alphabetical sorting (after weight-based sorting) by today.  I will request you and Steve for another round of testing later.

2020-11-09 18:21 UTC, Adnan-cds commented
Ready for review once again. @stephen-cox @finnlewis 

Both Directory facet types and Directory facet items should now be first sorted by weight and then label.  This means both Facet types and Facet items with equal weights will be sorted by their labels.

In the Directory facet listing page (i.e. /admin/content/directories/facets), sorting now happens based on Facet type, next weight, and then label.  This allows Facet items of the same Facet type to all appear together in this list.  This is to improve editor experience as per Steve's suggestion.

2020-11-16 09:24 UTC, stephen-cox approved these changes
Looks good @Adnan-cds Sorting is working as I would expect it; weight and then alphabetical. The change to the sort on the fact items page is also an improvement. Happy to approve this.

2020-11-16 11:06 UTC, merged

2020-11-16 11:06 UTC, Adnan-cds commented
Thanks Steve, thanks Finn.  I am merging this master.